## Netlify deploys
[build]
command = "npm run build"
publish = "dist"
## Headers
[[headers]] # Main rules
  for = "/*"
  [headers.values]
  cache-control = '''
    public,
    max-age=300'''
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
[[headers]] # Font files
  for = "/fonts/*"
  [headers.values]
  cache-control = '''
    public,
    max-age=31536000,
    immutable'''
[[headers]] # Favicon
  for = "/favicon.ico"
  [headers.values]
  cache-control = '''
    public,
    max-age=3600'''
# ## Redirects
# [[redirects]] # 404 error page
#   from = "/*"
#   to = "/404"
#   status = 404
